---

version : "3"

services : 

    EncryptDecrypt:
        image : hb.factory.showroom.aixom.tech/rnd/crypto:v1.0
        ports :
          - '8008:8008'
        

    Server :
        image : hb.factory.showroom.aixom.tech/rnd/server:v1.0

        ports :
          - '8000:8000'
        
    GenKey :
        image : hb.factory.showroom.aixom.tech/rnd/genkey:v1.0

        ports :
          - '7500:7500'

    Yolo : 
        image : hb.factory.showroom.aixom.tech/rnd/yolo:v4

        ports : 
          - '4040:4040'
        environment :
          - DISPLAY=$DISPLAY
          - QT_X11_NO_MITSHM=1
        volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix 