version: "3"

services:
  traefik:
    image: traefik:v2.3
    restart: always
    command:
      - --accesslog
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "8080:8080"
      
  encrypt:
    image: hb.factory.showroom.aixom.tech/general/client:v1.5
    restart: always
    environment:
      - APP_PORT=8008
      - APP_NAME=encrypt
    expose:
      - "8008"
    labels:
      - traefik.enable=true
      - traefik.http.routers.encrypt.rule=Host(`apt.he`) && PathPrefix(`/client/`)


  server:
    image: hb.factory.showroom.aixom.tech/general/server:v1.5
    restart: always
    environment:
      - APP_PORT=8000
      - APP_NAME=server
    expose:
      - "8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.rule=Host(`apt.he`) && Path(`/inference`)

  Yolo:
    image: hb.factory.showroom.aixom.tech/general/yolo:v1.5
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - APP_PORT=4040
      - APP_NAME=yolo
    expose:
      - "4040"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    labels:
      - traefik.enable=true
      - traefik.http.routers.yolo.rule=Host(`apt.he`) && Path(`/inference_yolo`)
